POST http://localhost:5001/mansion-espiritus-lkgoxs/us-central1/apiAi
Content-type: application/json

{
    "text": "Vale, qué hacemos",
    "language": "es",
    "conv": {
        "previousConversation": []        
    }
}

#####
POST https://apiai-sruiznnf5a-uc.a.run.app
Content-type: application/json

{
    "text": "Holissss",
    "language": "es",
    "conv": {
        "previousConversation": []        
    }
}