POST http://localhost:5001/mansion-espiritus-lkgoxs/us-central1/apiAi
Content-type: application/json

{
    "text": "Pues venga, hazlo",
    "language": "es",
    "conv": {
        "previousConversation": [
{
        "user": "USER",
        "sentence": "Dime tú qué hacer"
      },
      {
        "user": "DRON",
        "sentence": "¡Oh, claro! Porque soy un dron con todas las respuestas. ¿Qué tal si miras a tu alrededor y decides qué hacer?"
      }

        ]        
    }
}

#####
POST https://apiai-sruiznnf5a-uc.a.run.app
Content-type: application/json

{
    "text": "Holissss",
    "language": "es",
    "conv": {
        "previousConversation": []        
    }
}